/**
 * Location data for country and state/province dropdowns
 */

export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "India",
  "Germany",
  "France",
  "Brazil",
  "Mexico",
  "Japan",
  "China",
  "South Korea",
  "Singapore",
  "Ireland",
  "Netherlands",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Spain",
  "Italy",
  "Poland",
  "Portugal",
  "Belgium",
  "Austria",
  "New Zealand",
  "Israel",
  "United Arab Emirates",
  "Saudi Arabia",
  "South Africa",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Malaysia",
  "Indonesia",
  "Taiwan",
  "Hong Kong",
  "Turkey",
  "Russia",
  "Ukraine",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Greece",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Bangladesh",
  "Pakistan",
  "Sri Lanka",
  "Nepal",
  "Myanmar",
  "Cambodia",
  "Laos",
  "Mongolia",
  "Kazakhstan",
  "Uzbekistan",
  "Azerbaijan",
  "Georgia",
  "Armenia",
  "Lebanon",
  "Jordan",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Iraq",
  "Iran",
  "Afghanistan",
  "Bangladesh",
  "Bhutan",
  "Brunei",
  "Maldives",
  "Mauritius",
  "Seychelles",
  "Fiji",
  "Papua New Guinea",
  "Samoa",
  "Tonga",
  "Vanuatu",
  "Solomon Islands",
  "Palau",
  "Micronesia",
  "Marshall Islands",
  "Nauru",
  "Tuvalu",
  "Kiribati",
  "Other"
];

export const STATES_BY_COUNTRY = {
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "District of Columbia"
  ],
  "Canada": [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon"
  ],
  "United Kingdom": [
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland"
  ],
  "Australia": [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia"
  ],
  "India": [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry"
  ],
  "Germany": [
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia"
  ],
  "Brazil": [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins"
  ],
  "Mexico": [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas"
  ]
};

/**
 * Get states/provinces for a given country
 * @param {string} country - Country name
 * @returns {string[]} Array of state/province names, or empty array if not found
 */
export function getStatesForCountry(country) {
  return STATES_BY_COUNTRY[country] || [];
}

/**
 * Check if a country has states/provinces data
 * @param {string} country - Country name
 * @returns {boolean} True if states data exists for the country
 */
export function hasStatesData(country) {
  return country in STATES_BY_COUNTRY;
}
